language: java
jdk:
  - oraclejdk8
sudo: false
install: true
before_script:
- mvn install -q -U -Dmaven.test.redirectTestOutputToFile=true || true
script: mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'